### ISSUE TITLE
How to use mapBubbles & mapCountryData in the same map?

### ISSUE THREAD

**Issue by ONeillMB1** [AndySouth/rworldmap#5]
I would like to combine the mapCountryData and mapBubbles functions into one map so that I have a map with countries shaded by one variable and bubbles representing another. Below are examples of two maps I would like to merge:

![image](https://cloud.githubusercontent.com/assets/5341397/15366286/3cbad4e6-1ce9-11e6-8692-d90f633e94c9.png)

![image](https://cloud.githubusercontent.com/assets/5341397/15366314/5d657250-1ce9-11e6-9271-09562b89ef59.png)

**Comment by andysouth** [comment]
Try 'add=TRUE' in the 2nd.

**Comment by ONeillMB1** [comment]
Beautiful! Thank you!
